### ISSUE TITLE
First Release

### ISSUE THREAD

**Issue by awestlake87** [awestlake87/pyo3-asyncio#8]
## TODO:

- [x] Wrap up [guide PR](https://github.com/PyO3/pyo3/pull/1393)
- [x] Merge #3
- [x] Merge #7
- [x] Main fn proc macros? #10 
- [x] Resolve discussions around `into_future` / `into_coroutine` (#4, [guide PR](https://github.com/PyO3/pyo3/pull/1393))
- [x] Verify CI action passes with v0.13.2

## Post Release
- [x] Verify docs.rs links to `pyo3-asyncio` in guide
- [x] v0.13.0 tag
- [x] Verify crates.io and docs.rs links in README

**Comment by awestlake87** [comment]
I'm keeping the `other-runtimes` branch around for now since it's linked in some open issues.

**Comment by awestlake87** [comment]
Released and tagged `0.13.1` to fix docs.rs features
